#!/usr/bin/env python3

try:
    import requests
    import lxml.html
    import os
    import sys
    import time
    import traceback
    from PyQt5 import Qt
except Exception as e:
    print('')
    print('A fatal error occured while importing necessary libraries:')
    print('')
    traceback.print_exc()
    print('')
    print('Try running `pip3 install requests lxml pyqt5`')
    print('')
    input("Press Enter to continue...")
    sys.exit(1)

try:
    import config
except Exception as e:
    print('')
    print('A fatal error occured while parsing the config file:')
    print('')
    traceback.print_exc()
    print('')
    input("Press Enter to continue...")
    sys.exit(1)

#-----------
# Functions
#

def notify(title, message):
    print('> ' + title)
    print('> ' + message)
    sti = Qt.QSystemTrayIcon()
    sti.setIcon(Qt.QIcon('icon.jpg'))
    sti.show()
    sti.showMessage(title, message)


#------
# Main
#

def main():
    print('')
    print(' ======================== ')
    print('|| GT Course Watch v0.9 ||')
    print('||   By Kevin Abraham   ||')
    print(' ======================== ')
    print('')

    print('')
    print('TERM: ' + config.TERM)
    print('')

    for crn in config.CRNS:
        print('')
        print('CRN:  ' + crn)
        print('Fetching course info page from student information system... ',
            end='')

        html = requests.get(config.URL + 'bwckschd.p_disp_detail_sched?term_in='
            + config.TERM + '&crn_in=' + crn).text

        print('Parsing... ', end='')

        root = lxml.html.fromstring(html)
        dddefault = root.find_class('dddefault')
        ddlabel = root.find_class('ddlabel')

        print('Verifying... ', end='')

        if len(dddefault) == 4:
            waitlist = False
        elif len(dddefault) == 7:
            print('Waitlist detected.')
            waitlist = True
        else:
            print('')
            print('Unexpected results! Check the CRN number!')
            print('')
            continue

        if len(dddefault) > 0:
            courseName = ddlabel[0].text
            print('')
            print('Course: ' + courseName)
        else:
            courseName = ''
            print('')
            print('Couldn\'t get course name!')

        print('')

        print ('Checking seat availability...')
        if int(dddefault[3].text) != 0:
            notify('Seat Available for CRN ' + crn + '!', courseName)
            print('')
            continue

        if (not config.WLDIS) and waitlist:
            print ('Checking waitlist seat availability...')
            if int(dddefault[6].text) != 0:
                notify('Waitlist Seat Available for CRN ' + crn + '!',
                    courseName)
                continue

        print('No Seat Available for CRN ' + crn + '.')
        print('')

    print('')
    print('All done.')
    print('')

def main2():
    try:
        print('\033[H\033[J')
        main()
    except Exception as e:
        print('')
        print('A FATAL ERROR OCCURED:')
        traceback.print_exc()
        print('')
    finally:
        Qt.QTimer.singleShot(5000, main2)

if __name__ == '__main__':
    app = Qt.QApplication(sys.argv)
    Qt.QTimer.singleShot(0, main2)
    sys.exit(app.exec_())

